export const greetings = {
  "Hello, sunshine!": "Search below to explore today's weather",
  "Let's chase some clouds": "Start by entering your location",
  "Good morning, weather watcher!": "Type a place and hit search to begin",
  "Feeling breezy?": "Search for any city and check its vibe",
  "🌦 What's the sky up to?": "Enter a location to find out",
  "Hello from the clouds ☁️": "Search below and discover your forecast",
  "Sky check, anyone?": "Drop a location and see what’s up there",
  "Catch the climate": "Search your city to begin",
  "Ready for a weather dive?": "Start by typing in your location",
  "Forecast fun awaits!": "Search for a place below",
  "🌤️ What's it like out there?": "Let’s find out. Enter a place",
  "Curious about the clouds?": "Search a location and see what’s brewing",
  "Sky’s the limit": "Pick a place and explore the weather",
  "Weather whisperer reporting in": "Where to today?",
  "Tap into today": "Search to see the forecast",
  "☀️ Rain or shine?": "Let’s check your city",
  "One search away from the skies": "Type a location below",
  "Forecast magic starts here": "Search any place to begin",
  "Temperature tales await": "Search your city below",
  "Where to next?": "Search a location to begin your weather journey",
  "Hey there, sky gazer": "Type in a city and let's see what’s up",
  "Is it jacket weather?": "Search below to know",
  "It’s weather o’clock!": "Pick a spot and hit search",
  "Skies ahead!": "Drop a location to begin",
  "Cloud curious?": "Let’s look it up together",
  "Just one search away...": "Find out what the sky’s cooking",
  "Your weather guide, reporting for duty": "Enter your destination",
  "Big weather energy today": "Check your local vibe",
  "☁️ Wondering what to wear?": "Search the weather first",
  "Adventure starts with a forecast": "Type in a place and go",
  "Let's make it rain": "Type a city and see the forecast",
  "Clear skies ahead": "Search for your spot in the sky",
  "Chasing the weather": "Let's start by entering a place",
  "The sky’s calling": "Where’s your weather adventure today?",
  "Catch the breeze": "Type in a location to get started",
  "Weather vibes only": "Check the forecast for your city",
  "🌧️ Ready for rain?": "Start by searching your city",
  "Your weather journey starts here": "Type in a location to explore",
  "Forecasting fun": "Where’s your next adventure? Search below",
  "Weather explorer": "Enter a place to begin your weather discovery",
  "Today's forecast awaits": "Type in your location to start",
  "The weather's waiting for you": "Search your city to get started",
  "Clouds and sunshine ahead": "Enter a place to check the forecast",
  "All about the forecast": "Type a location to get started",
  "Weather wizardry starts here": "Search your city for details",
  "Hello, sky lover": "Enter a place and see what’s brewing",
  "Chasing sunbeams": "Start by searching for your city",
  "Wind in your hair": "Type a location to check the weather",
  "☀️ Let’s see what’s shining": "Enter your city to find out",
  "Catch a breeze": "Search for a place to begin",
  "Weather's in the air": "Type your location and let’s dive in",
  "What's the weather mood?": "Search a place to see",
  "Ready for a forecast adventure?": "Enter a location below",
  "Curious about today’s skies?": "Let’s start by typing a place",
  "Feel the weather pulse": "Pick a city and let’s check it out",
  "On a weather quest?": "Search for your next stop below",
  "Clear skies or stormy?": "Let’s find out! Enter a location",
  "What’s the weather vibe?": "Type in a place to start",
  "Sailing through the skies": "Enter your city to see the forecast",
  "Check the clouds with me": "Type a place and hit search",
  "Weather, anyone?": "Let’s search your city for the forecast",
  "Step into the forecast": "Enter a location and begin",
  "Your forecast adventure awaits": "Type a place and let’s go",
  "Look up at the sky": "Let’s check the weather for your city",
  "Looking for clear skies?": "Search below to find out",
  "Sunshine or showers?": "Start by typing a city",
  "Breezes or calm?": "Search for your location to find out",
  "Weather wonders await": "Pick a place and search below",
  "The sky is the limit": "Enter your city to check the forecast",
  "Forecasting the day": "Type in your location to get started",
  "Let's check the horizon": "Enter a city and let’s explore",
  "What's in the weather crystal ball?": "Start by searching your location",
  "Weather vibes incoming": "Type a place to check out today’s forecast",
  "It's weather discovery time": "Search for a place below",
  "Take a look at the sky": "Enter your city and let’s dive in",
  "Today's forecast is calling": "Let’s see what’s ahead, search below",
  "Looking for a weather guide?": "Start by typing a location",
  "Ready for some sunshine?": "Type in a place and find out",
  "Let's see what the day holds": "Search for your city’s forecast",
  "Discover your weather today": "Enter a location below to get started",
  "Hey, sky gazer!": "Type a location below and let the forecast flow",
  "What's the weather vibe?": "Pop in a city and let's check the sky",
  "Forecast time!": "Enter a place and we’ll handle the clouds",
  "Hello, sunshine! (or rain?)": "Search a spot to see what’s up above",
  "Sky check, initiated": "Where to? Your next forecast is one search away",
  "Let’s chase some clouds": "Type in a location and let's see what they’re up to",
  "Weather, served fresh": "Just add a city below to get the latest conditions",
  "Temp check, coming up": "Where should we scan the skies today?",
  "What's cookin' in the clouds?": "Search a place and we’ll find out together",
  "Weather curious? Dive in": "Type in a city to get your instant forecast fix",
  "Skies await your command": "Your next location is one search away",
  "Your daily sky scoop": "Enter any place and we’ll fetch the goods",
  "One tap to forecast magic": "Just search to unlock weather wonders",
  "Sun or storm, let’s see": "Enter a location and we’ll peek at the skies",
  "Up for a weather surprise?": "Search a city and embrace the unknown"
};
