export const mobileGreetings = {
  "Weather, served fresh": "Just add a city below to get the latest conditions",
  "Forecast magic awaits": "Drop your location and let the weather wizardry begin",
  "Sky check, initiated": "Enter any city for instant atmospheric vibes",
  "Temperature tales ready": "Search your spot below for today's climate story",
  "Weather wizardry here": "Type location to unlock the secrets of the skies",
  "Forecast fun activated": "Add your city and dive into weather wonderland",
  "Climate curious today?": "Search below to discover what's brewing up there",
  "Sky's calling you": "Enter location for the inside scoop on conditions",
  "Weather vibes incoming": "Type city for fresh forecast straight from the clouds",
  "Sunshine or storms?": "Search your spot to see what nature has planned",
  "Cloud chasing mode": "Drop location and explore the atmospheric adventure",
  "Forecast adventure waits": "Enter city below to start your weather journey",
  "Weather wisdom unlocked": "Search location for atmospheric insights and more",
  "Sky stories await": "Type your city in for tales from above",
  "Temperature check time": "Add location for instant data from the atmosphere",
  "Weather magic brewing": "Search city for live updates from the sky gods",
  "Forecast feels ready": "Enter your spot below for climate vibes check",
  "Climate check engaged": "Type location to begin your atmospheric scan",
  "Sky dive activated": "Search city for deep dive into current conditions",
  "Weather wonder time": "Drop location and discover today's atmospheric mood",
  "Temp tales loading": "Enter city for the complete temperature story",
  "Forecast flow started": "Search your place below for weather wave details",
  "Weather wave incoming": "Type location for fresh vibes from the stratosphere",
  "Sky scan ready": "Add city for instant atmospheric health check",
  "Climate quest begins": "Enter location to explore today's weather mystery",
  "Weather pulse active": "Search city for live feel of atmospheric energy",
  "Forecast fever on": "Type your spot below for weather addiction fix",
  "Sky peek mode": "Drop location for quick glimpse into weather reality",
  "Weather wisdom waits": "Enter city for insights from the weather masters",
  "Temperature time now": "Search location for temps straight from the source",
  "Forecast fun loading": "Type city for your daily dose of weather adventure",
  "Weather vibe check": "Add location for instant atmospheric mood reading",
  "Sky story time": "Enter your spot below for today's weather narrative",
  "Climate catch active": "Search city for conditions caught fresh from the air",
  "Weather win incoming": "Type location for victory over weather uncertainty",
  "Forecast fix ready": "Drop city for solution to your weather curiosity",
  "Sky snap engaged": "Enter location for instant pic of atmospheric conditions",
  "Weather whiz mode": "Search your place below for expert weather intel",
  "Temperature talk time": "Type city for the full conversation with climate",
  "Forecast feels alive": "Add location for live vibes from the living sky"
};
